controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t

  - name: right_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_gripper_finger_joint
